name: LIVE - Build and Publish
on:
  release:
    types: [published]

jobs:
  version:
    name: Get version
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version from package.json
        id: get_version
        run: |-
          echo ::set-output name=VERSION::$(cat package.json \
          | grep version \
          | head -1 \
          | awk -F: '{ print $2 }' \
          | sed 's/[",]//g' \
          | tr -d '[[:space:]]')

      - name: echo values
        run: |-
          echo "VERSION ${{ steps.get_version.outputs.VERSION }}"

      - name: echo values
        run: |-
          echo "VERSION ${{ steps.get_version.outputs.VERSION }}"
          echo "SHA $GITHUB_SHA"
          echo "REF $GITHUB_REF"
